[workspace]
members = [
    "crates/core",
    "crates/desktop", 
    "crates/cli"
]
resolver = "2"

[workspace.dependencies]
# Async runtime
tokio = { version = "1.35", features = ["full"] }

# Serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# Utilities
uuid = { version = "1.6", features = ["v4", "serde"] }
chrono = { version = "0.4", features = ["serde"] }
anyhow = "1.0"
thiserror = "1.0"

# Logging
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

# Bluetooth for Windows
btleplug = "0.11"

# Async utilities
futures = "0.3"

# Cryptography
ring = "0.17"
chacha20poly1305 = "0.10"
x25519-dalek = "2.0"
ed25519-dalek = "2.0"
rand = "0.8"

# UI frameworks
eframe = "0.24"
egui = "0.24"

# CLI
clap = { version = "4.4", features = ["derive"] }

# File operations
dirs = "5.0"
bytes = { version = "1.5", features = ["serde"] }
