[package]
name = "bitchat-core"
version = "0.1.0"
edition = "2021"
description = "Core BitChat functionality"

[dependencies]
# Workspace dependencies
tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
uuid = { workspace = true }
chrono = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
btleplug = { workspace = true }
futures = { workspace = true }
ring = { workspace = true }
chacha20poly1305 = { workspace = true }
x25519-dalek = { workspace = true }
ed25519-dalek = { workspace = true }
rand = { workspace = true }
bytes = { workspace = true }
dirs = { workspace = true }

# Additional dependencies
tokio-stream = "0.1"
