[package]
name = "bitchat-core"
version = "0.1.0"
edition = "2021"
description = "Core SecureMesh library with iOS/Android compatibility"

[dependencies]
# Workspace dependencies
tokio = { workspace = true }
futures = { workspace = true }
btleplug = { workspace = true, optional = true }
ring = { workspace = true }
chacha20poly1305 = { workspace = true }
x25519-dalek = { workspace = true }
ed25519-dalek = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
uuid = { workspace = true }
chrono = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
hex = { workspace = true }
rand = { workspace = true }
fastrand = { workspace = true }
tokio-stream = { workspace = true }

[features]
default = ["bluetooth"]
bluetooth = ["btleplug"]