[package]
name = "bitchat-desktop"
version = "0.1.0"
edition = "2021"
description = "BitChat desktop application for Windows"

[[bin]]
name = "bitchat-desktop"
path = "src/main.rs"

[dependencies]
bitchat-core = { path = "../core" }

tokio = { workspace = true, features = ["rt-multi-thread"] }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
anyhow = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }

# GUI framework
eframe = { workspace = true }
egui = { workspace = true }

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3", features = ["winuser", "consoleapi"] }