[package]
name = "secure-mesh-desktop"
version = "0.1.0"
edition = "2021"
description = "SecureMesh Desktop Application"

[[bin]]
name = "desktop"
path = "src/main.rs"

[dependencies]
# Local dependencies
bitchat-core = { path = "../core" }

# Workspace dependencies
tokio = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
eframe = { workspace = true }
egui = { workspace = true }
chrono = { workspace = true }

# Windows-specific fix
[target.'cfg(windows)'.dependencies]
winapi = { workspace = true }